<?php

/**
 * @package CRM
 * @copyright CiviCRM LLC (c) 2004-2019
 *
 * Generated from /buildkit/build/dmaster/sites/default/files/civicrm/ext/mailchimpsync/xml/schema/CRM/Mailchimpsync/MailchimpsyncUpdate.xml
 * DO NOT EDIT.  Generated by CRM_Core_CodeGen
 * (GenCodeChecksum:530b27b2a33ec09634feac803224e0bf)
 */

/**
 * Database access object for the MailchimpsyncUpdate entity.
 */
class CRM_Mailchimpsync_DAO_MailchimpsyncUpdate extends CRM_Core_DAO {

  /**
   * Static instance to hold the table name.
   *
   * @var string
   */
  public static $_tableName = 'civicrm_mailchimpsync_update';

  /**
   * Should CiviCRM log any modifications to this table in the civicrm_log table.
   *
   * @var bool
   */
  public static $_log = FALSE;

  /**
   * Unique MailchimpsyncUpdate ID
   *
   * @var int
   */
  public $id;

  /**
   * FK to MailchimpsyncCache ID
   *
   * @var int
   */
  public $mailchimpsync_cache_id;

  /**
   * FK to Mailchimpsync Batch
   *
   * @var int
   */
  public $mailchimpsync_batch_id;

  /**
   * @var TEXT
   */
  public $data;

  /**
   * @var bool
   */
  public $completed;

  /**
   * Class constructor.
   */
  public function __construct() {
    $this->__table = 'civicrm_mailchimpsync_update';
    parent::__construct();
  }

  /**
   * Returns foreign keys and entity references.
   *
   * @return array
   *   [CRM_Core_Reference_Interface]
   */
  public static function getReferenceColumns() {
    if (!isset(Civi::$statics[__CLASS__]['links'])) {
      Civi::$statics[__CLASS__]['links'] = static::createReferenceColumns(__CLASS__);
      Civi::$statics[__CLASS__]['links'][] = new CRM_Core_Reference_Basic(self::getTableName(), 'mailchimpsync_cache_id', 'civicrm_mailchimpsync_cache', 'id');
      Civi::$statics[__CLASS__]['links'][] = new CRM_Core_Reference_Basic(self::getTableName(), 'mailchimpsync_batch_id', 'civicrm_mailchimpsync_batch', 'id');
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'links_callback', Civi::$statics[__CLASS__]['links']);
    }
    return Civi::$statics[__CLASS__]['links'];
  }

  /**
   * Returns all the column names of this table
   *
   * @return array
   */
  public static function &fields() {
    if (!isset(Civi::$statics[__CLASS__]['fields'])) {
      Civi::$statics[__CLASS__]['fields'] = [
        'id' => [
          'name' => 'id',
          'type' => CRM_Utils_Type::T_INT,
          'description' => CRM_Mailchimpsync_ExtensionUtil::ts('Unique MailchimpsyncUpdate ID'),
          'required' => TRUE,
          'where' => 'civicrm_mailchimpsync_update.id',
          'table_name' => 'civicrm_mailchimpsync_update',
          'entity' => 'MailchimpsyncUpdate',
          'bao' => 'CRM_Mailchimpsync_DAO_MailchimpsyncUpdate',
          'localizable' => 0,
        ],
        'mailchimpsync_cache_id' => [
          'name' => 'mailchimpsync_cache_id',
          'type' => CRM_Utils_Type::T_INT,
          'description' => CRM_Mailchimpsync_ExtensionUtil::ts('FK to MailchimpsyncCache ID'),
          'where' => 'civicrm_mailchimpsync_update.mailchimpsync_cache_id',
          'table_name' => 'civicrm_mailchimpsync_update',
          'entity' => 'MailchimpsyncUpdate',
          'bao' => 'CRM_Mailchimpsync_DAO_MailchimpsyncUpdate',
          'localizable' => 0,
        ],
        'mailchimpsync_batch_id' => [
          'name' => 'mailchimpsync_batch_id',
          'type' => CRM_Utils_Type::T_INT,
          'description' => CRM_Mailchimpsync_ExtensionUtil::ts('FK to Mailchimpsync Batch'),
          'where' => 'civicrm_mailchimpsync_update.mailchimpsync_batch_id',
          'table_name' => 'civicrm_mailchimpsync_update',
          'entity' => 'MailchimpsyncUpdate',
          'bao' => 'CRM_Mailchimpsync_DAO_MailchimpsyncUpdate',
          'localizable' => 0,
        ],
        'data' => [
          'name' => 'data',
          'type' => CRM_Utils_Type::T_TEXT,
          'title' => CRM_Mailchimpsync_ExtensionUtil::ts('Data'),
          'required' => TRUE,
          'where' => 'civicrm_mailchimpsync_update.data',
          'table_name' => 'civicrm_mailchimpsync_update',
          'entity' => 'MailchimpsyncUpdate',
          'bao' => 'CRM_Mailchimpsync_DAO_MailchimpsyncUpdate',
          'localizable' => 0,
        ],
        'completed' => [
          'name' => 'completed',
          'type' => CRM_Utils_Type::T_BOOLEAN,
          'title' => CRM_Mailchimpsync_ExtensionUtil::ts('Completed'),
          'required' => TRUE,
          'where' => 'civicrm_mailchimpsync_update.completed',
          'default' => '0',
          'table_name' => 'civicrm_mailchimpsync_update',
          'entity' => 'MailchimpsyncUpdate',
          'bao' => 'CRM_Mailchimpsync_DAO_MailchimpsyncUpdate',
          'localizable' => 0,
        ],
      ];
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'fields_callback', Civi::$statics[__CLASS__]['fields']);
    }
    return Civi::$statics[__CLASS__]['fields'];
  }

  /**
   * Return a mapping from field-name to the corresponding key (as used in fields()).
   *
   * @return array
   *   Array(string $name => string $uniqueName).
   */
  public static function &fieldKeys() {
    if (!isset(Civi::$statics[__CLASS__]['fieldKeys'])) {
      Civi::$statics[__CLASS__]['fieldKeys'] = array_flip(CRM_Utils_Array::collect('name', self::fields()));
    }
    return Civi::$statics[__CLASS__]['fieldKeys'];
  }

  /**
   * Returns the names of this table
   *
   * @return string
   */
  public static function getTableName() {
    return self::$_tableName;
  }

  /**
   * Returns if this table needs to be logged
   *
   * @return bool
   */
  public function getLog() {
    return self::$_log;
  }

  /**
   * Returns the list of fields that can be imported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &import($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getImports(__CLASS__, 'mailchimpsync_update', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of fields that can be exported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &export($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getExports(__CLASS__, 'mailchimpsync_update', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of indices
   *
   * @param bool $localize
   *
   * @return array
   */
  public static function indices($localize = TRUE) {
    $indices = [];
    return ($localize && !empty($indices)) ? CRM_Core_DAO_AllCoreTables::multilingualize(__CLASS__, $indices) : $indices;
  }

}
