site_name: Mailchimp Sync
repo_url: https://github.com/artfulrobot/mailchimpsync
theme: material

pages:
- Home: index.md
- Tutorial: tutorial.md
- How Tos:
    - 'How to sync an existing audience': howto/sync-existing.md
    - 'How to run a sync': howto/run-sync.md
- Discussions:
    - 'Mailchimp Issues': discussion/mailchimp-issues.md
    - 'Optimisation': discussion/sql-optimisation.md
- Reference:
    - 'API Reference': reference/api.md
    - 'Table Reference': reference/tables.md
    - 'Sync Details': reference/sync-detail.md

markdown_extensions:
  - attr_list
  - admonition
  - def_list
  - codehilite
  - toc(permalink=true)
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.tilde
  - pymdownx.betterem
  - pymdownx.mark

