site_name: Mailchimp Sync
repo_url: https://github.com/artfulrobot/mailchimpsync
theme: material

pages:
- Home: index.md
- Tutorial: tutorial.md
- How Tos:
    - 'How to sync an existing audience': howto/sync-existing.md
    - 'How to run a sync': howto/run-sync.md
- Discussions: discussion/index.md
- Reference: reference/index.md
- Reference: reference/sync-detail.md
- Quick Start: quick-start.md

markdown_extensions:
  - attr_list
  - admonition
  - def_list
  - codehilite
  - toc(permalink=true)
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.tilde
  - pymdownx.betterem
  - pymdownx.mark

